"""The collector graph's shape, drawn from the graph itself.

The topology is decided by `build_collector_graph` and by `routing.py`, and
neither asks a node what it does. So the picture needs no model, no MCP session
and no credentials -- which is what makes it something a test can check on every
run rather than a screenshot somebody has to remember to retake.

    python -m aiops_rca.graph.diagram > docs/collector-graph.md
"""

from collections.abc import Mapping
from typing import Any

from aiops_rca.graph.builder import CollectorNodes, build_collector_graph
from aiops_rca.graph.state import InvestigationState

_HEADING = "# Collector graph"

_PREAMBLE = """
Generated by `python -m aiops_rca.graph.diagram`. `tests/test_graph_diagram.py`
compares the edges below against the compiled graph, so this cannot drift from
the code without a test saying so.

Solid arrows are unconditional; dashed ones are the routing decisions in
`graph/routing.py`.
"""


async def _unused(_: InvestigationState) -> Mapping[str, Any]:
    """Stands in for a node while the drawing is made."""
    return {}


def collector_graph() -> Any:
    """The compiled collector graph with every node stubbed out.

    Built from the dataclass fields rather than a list written here, so a node
    added to `CollectorNodes` appears in the drawing without a second edit.
    """
    return build_collector_graph(
        CollectorNodes(
            **{field: _unused for field in CollectorNodes.__dataclass_fields__},
        ),
    )


def collector_graph_mermaid() -> str:
    return collector_graph().get_graph().draw_mermaid()


def collector_graph_document() -> str:
    return (
        f"{_HEADING}\n{_PREAMBLE}\n"
        f"```mermaid\n{collector_graph_mermaid().strip()}\n```\n"
    )


if __name__ == "__main__":
    print(collector_graph_document(), end="")
